# Generated by Django 4.0.4 on 2022-05-27 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_female',
            name='date',
            field=models.CharField(blank=True, default='27:05/10:02 AM', max_length=20),
        ),
        migrations.AddField(
            model_name='cash_female',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cash_female',
            name='sex',
            field=models.CharField(blank=True, choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=20),
        ),
        migrations.AddField(
            model_name='cash_male',
            name='date',
            field=models.CharField(blank=True, default='27:05/10:02 AM', max_length=20),
        ),
        migrations.AddField(
            model_name='cash_male',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cash_male',
            name='sex',
            field=models.CharField(blank=True, choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cash_female',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cash_female',
            name='dollar',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='cash_female',
            name='guest_name',
            field=models.CharField(blank=True, max_length=26),
        ),
        migrations.AlterField(
            model_name='cash_female',
            name='riel',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='cash_male',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cash_male',
            name='dollar',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cash_male',
            name='guest_name',
            field=models.CharField(blank=True, max_length=26),
        ),
        migrations.AlterField(
            model_name='cash_male',
            name='riel',
            field=models.IntegerField(blank=True),
        ),
    ]
