# Generated by Django 4.0.4 on 2022-06-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cash_female_date_cash_female_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_female',
            name='date',
            field=models.CharField(blank=True, default='04:06/12:59 PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='cash_male',
            name='date',
            field=models.CharField(blank=True, default='04:06/12:59 PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='cash_male',
            name='sex',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
