# Generated by Django 4.0.4 on 2022-06-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cash_female_date_alter_cash_female_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash_female',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterModelOptions(
            name='cash_male',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterField(
            model_name='cash_female',
            name='date',
            field=models.CharField(blank=True, default='05:06/02:51 AM', max_length=20),
        ),
        migrations.AlterField(
            model_name='cash_female',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cash_male',
            name='date',
            field=models.CharField(blank=True, default='05:06/02:51 AM', max_length=20),
        ),
        migrations.AlterField(
            model_name='cash_male',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
